import {
  DEFAULT_FORM_BUTTON_TEXTS,
  DEFAULT_TOAST_HEADERS,
  DEFAULT_INPUTS_TEXTS,
} from './default_texts'

export {
  DEFAULT_FORM_BUTTON_TEXTS,
  DEFAULT_TOAST_HEADERS,
  DEFAULT_INPUTS_TEXTS,
}
